name: CodeGuardiansReport

on: [pull_request]

jobs:
  execute-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out repository code

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install agency-swarm requests

      - name: Run Python script
        run: python ./CodeGuardiansAgency/agency.py
